import { Section, Text } from "@react-email/components"
import type { ZabradliConfType } from "@/lib/schemas"
import type { ConfPhotos } from "@/types"
import { zabradliSkloOptions } from "@/lib/konf-content"
import {
  type Lang,
  localeTags,
  mailContent,
  motivLabels,
  stepZabradliContent,
  zabMailContent,
  zabradliMaterialLabels,
  zabradliSkloLabels,
} from "@/lib/translations"
import {
  CompanyCard,
  DataRow,
  MailFooter,
  MailShell,
  Masthead,
  PhotoCard,
  SectionHead,
  mailColors,
  mailStyles,
} from "@/components/mail-theme"

/**
 * Potvrzovací e-mail konfigurátoru zábradlí. Skladbu i styly sdílí s `ConfMail`
 * (oplocení) a `PergMail` (pergoly) přes `components/mail-theme.tsx` — liší se
 * jen obsah tabulky: sady rozměrů a výplň.
 *
 * `lang` posílá `sendZabradliConf` ze stejné prop, jakou dostal konfigurátor z `?lang=`.
 */
export const ZabMail = (data: ZabradliConfType, photos: ConfPhotos, lang: Lang = "cs") => {
  const t = mailContent[lang] ?? mailContent.cs
  const z = zabMailContent[lang] ?? zabMailContent.cs
  const zt = stepZabradliContent[lang] ?? stepZabradliContent.cs
  const locale = localeTags[lang] ?? localeTags.cs

  const materialLabel =
    (data.zabradliMaterial && (zabradliMaterialLabels[lang] ?? zabradliMaterialLabels.cs)[data.zabradliMaterial]) ||
    data.zabradliMaterial ||
    z.notSpecified

  /**
   * Odstín skla chodí z konfigurátoru jako malými písmeny (`ColorSwatchGroup` ukládá
   * `color.toLowerCase()`), kdežto `zabradliSkloLabels` je klíčovaný původním názvem —
   * překlad proto vede přes `zabradliSkloOptions`.
   */
  const skloLabel = (() => {
    if (!data.zabradliSklo) return z.notSpecified
    const opt = zabradliSkloOptions.find((c) => c.color.toLowerCase() === data.zabradliSklo)
    if (!opt) return data.zabradliSklo
    return (zabradliSkloLabels[lang] ?? zabradliSkloLabels.cs)[opt.color] ?? opt.color
  })()

  /** Motiv se ukládá jako `src` z `motivy`, což je i klíč v `motivLabels`. */
  const motivLabel =
    (data.zabradliMotiv && (motivLabels[lang] ?? motivLabels.cs)[data.zabradliMotiv]) ||
    data.zabradliMotiv ||
    z.notSpecified

  /** Jen sady, které zákazník opravdu vyplnil — prázdné řádky v poli e-mail nezajímají. */
  const sizes = (data.rozmeryZabradli ?? [])
    .slice(0, Math.max(0, Number(data.celkemZabradli ?? 0)))
    .filter((r) => r && (Number(r.vyska) > 0 || Number(r.delka) > 0 || Number(r.pocet) > 0))

  const heroPhoto = photos?.ploty?.[0]

  return (
    <MailShell lang={lang} preview={t.preview}>
      <Masthead eyebrow={t.eyebrow} headline={z.headline} logoAlt={t.logoAlt} />

      <Section className="k-pad" style={mailStyles.body}>
        <Text style={mailStyles.lead}>{`${t.salutation} ${data.fullname},`}</Text>
        <Text style={mailStyles.text}>{t.intro}</Text>
        <Text style={mailStyles.text}>{t.intro2}</Text>
      </Section>

      {heroPhoto && (
        <>
          <SectionHead num="01" label={t.productsHeading} />
          <Section className="k-pad" style={{ ...mailStyles.sectionWrap, margin: "18px 0 0" }}>
            <PhotoCard src={heroPhoto} caption={zt.productTitle} alt={zt.productTitle} />
          </Section>
        </>
      )}

      {/* Konfigurace zábradlí */}
      <SectionHead num={heroPhoto ? "02" : "01"} label={z.configHeading} />
      <Section className="k-pad" style={{ ...mailStyles.sectionWrap, margin: "18px 0 0" }}>
        <Section style={mailStyles.dataTable}>
          <DataRow label={z.zabradliLabel} value={zt.productTitle} />
        </Section>

        {sizes.map((row, i) => (
          <Section key={i}>
            {/* Nadpis sady se vypisuje jen když jich je víc — u jediné by byl balast. */}
            {sizes.length > 1 && <Text style={mailStyles.subHead}>{`${z.sizeLabel} ${i + 1}`}</Text>}
            <Section style={mailStyles.dataTable}>
              <DataRow label={z.height} value={`${row.vyska ?? "—"} mm`} />
              <DataRow label={z.width} value={`${row.delka ?? "—"} mm`} />
              <DataRow label={z.count} value={`${row.pocet ?? "—"} ${z.pieces}`} />
            </Section>
          </Section>
        ))}

        <Text style={mailStyles.subHead}>{z.moreHeading}</Text>
        <Section style={mailStyles.dataTable}>
          <DataRow label={z.material} value={materialLabel} />
          {/* Sklo a hliník se vylučují — schéma vynucuje vyplněné právě to pole,
              které odpovídá zvolenému materiálu (viz `zabradliSchema.check`). */}
          {data.zabradliMaterial === "sklo" ? (
            <DataRow label={z.glass} value={skloLabel} />
          ) : (
            <DataRow label={z.motiv} value={motivLabel} />
          )}
        </Section>

        <Text style={{ ...mailStyles.footerSmall, color: mailColors.mutedSoft, margin: "8px 0 0" }}>
          {z.autoGenerated}
        </Text>
      </Section>

      {/* Údaje zákazníka */}
      <SectionHead num={heroPhoto ? "03" : "02"} label={t.yourInfoHeading} />
      <Section className="k-pad" style={{ ...mailStyles.sectionWrap, margin: "18px 0 0" }}>
        <Section style={mailStyles.dataTable}>
          <DataRow label={t.fullName} value={data.fullname} />
          <DataRow label={t.emailLabel} value={data.email} />
          <DataRow label={t.phoneLabel} value={data.phoneNumber} />
          <DataRow label={t.addressLabel} value={`${data.address}, ${data.obec}, ${data.zip}`} />
          {data.company && <DataRow label={t.companyLabel} value={data.company} />}
          {data.message && <DataRow label={t.messageLabel} value={data.message} />}
          <DataRow label={t.dateLabel} value={new Date().toLocaleDateString(locale)} />
        </Section>
      </Section>

      <SectionHead num={heroPhoto ? "04" : "03"} label={t.companyHeading} />
      <CompanyCard t={t} />

      <MailFooter t={t} />
    </MailShell>
  )
}

export default ZabMail
