import { Section, Text } from "@react-email/components"
import type { ZakladyType } from "@/lib/schemas"
import {
  type Lang,
  localeTags,
  mailContent,
  zakladyContent,
  zakladyMailContent,
} from "@/lib/translations"
import {
  CompanyCard,
  DataRow,
  MailFooter,
  MailShell,
  Masthead,
  SectionHead,
  mailColors,
  mailStyles,
} from "@/components/mail-theme"

/**
 * E-mail poptávky stavební přípravy a základů (/konf/zaklady). Skladbu i styly sdílí
 * s `ConfMail`/`ZabMail`/`PergMail` přes `components/mail-theme.tsx`.
 *
 * Oproti konfigurátorům tu není žádná konfigurace produktu — jádrem je zaškrtnutý
 * rozsah prací (`sluzby`) a volný popis situace, takže sekce jsou jen tři.
 *
 * `attachmentCount` se předává zvlášť: přílohy jdou do e-mailu přes nodemailer,
 * v datech poptávky nejsou, ale příjemce potřebuje vidět, že tam něco je.
 */
export const ZakladyMail = (
  data: ZakladyType,
  lang: Lang = "cs",
  attachmentCount = 0,
) => {
  const t = mailContent[lang] ?? mailContent.cs
  const z = zakladyMailContent[lang] ?? zakladyMailContent.cs
  const zc = zakladyContent[lang] ?? zakladyContent.cs
  const locale = localeTags[lang] ?? localeTags.cs

  /** Id → lokalizovaný popisek; neznámé id (starší poptávka) projde v původním tvaru. */
  const sluzbyLabels = (data.sluzby ?? []).map(
    (id) => zc.sluzby.find((s) => s.id === id)?.label ?? id,
  )

  return (
    <MailShell lang={lang} preview={z.preview}>
      <Masthead eyebrow={z.eyebrow} headline={z.headline} logoAlt={t.logoAlt} />

      <Section className="k-pad" style={mailStyles.body}>
        <Text style={mailStyles.lead}>{`${t.salutation} ${data.name},`}</Text>
        <Text style={mailStyles.text}>{z.intro}</Text>
        <Text style={mailStyles.text}>{z.intro2}</Text>
      </Section>

      {/* Rozsah prací */}
      <SectionHead num="01" label={z.scopeHeading} />
      <Section className="k-pad" style={{ ...mailStyles.sectionWrap, margin: "18px 0 0" }}>
        <Section style={mailStyles.dataTable}>
          {sluzbyLabels.length > 0 ? (
            sluzbyLabels.map((label, i) => (
              <DataRow key={label} label={`${String(i + 1).padStart(2, "0")}`} value={label} />
            ))
          ) : (
            <DataRow label={z.scopeLabel} value={z.notSpecified} />
          )}
        </Section>

        <Text style={mailStyles.subHead}>{z.situationHeading}</Text>
        <Section style={mailStyles.dataTable}>
          <DataRow label={z.placeLabel} value={data.misto} />
          <DataRow label={z.attachmentsLabel} value={String(attachmentCount)} />
        </Section>
        <Text style={mailStyles.text}>{data.msg}</Text>

        <Text style={{ ...mailStyles.footerSmall, color: mailColors.mutedSoft, margin: "8px 0 0" }}>
          {z.autoGenerated}
        </Text>
      </Section>

      {/* Údaje zákazníka */}
      <SectionHead num="02" label={t.yourInfoHeading} />
      <Section className="k-pad" style={{ ...mailStyles.sectionWrap, margin: "18px 0 0" }}>
        <Section style={mailStyles.dataTable}>
          <DataRow label={t.fullName} value={data.name} />
          <DataRow label={t.emailLabel} value={data.email} />
          <DataRow label={t.phoneLabel} value={data.tel} />
          <DataRow label={z.placeLabel} value={data.misto} />
          <DataRow label={t.dateLabel} value={new Date().toLocaleDateString(locale)} />
        </Section>
      </Section>

      <SectionHead num="03" label={t.companyHeading} />
      <CompanyCard t={t} />

      <MailFooter t={t} />
    </MailShell>
  )
}

export default ZakladyMail
